language: node_js
node_js:
  - '10'
services:
  - xvfb
cache:
  directories:
    - ./node_modules
jobs:
  include:
    - stage: test
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      script: npm run e2e
      name: e2e
    - script: npm run lint
      name: lint
