language: node_js
node_js:
  - '10'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
jobs:
  include:
    - stage: test
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      script: npm run lint
    - script: npm run e2e
